name: Deploy Sphinx Site to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Python and Sphinx
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install Sphinx and Verify Installation
        run: |
          pip install sphinx
          sphinx-build --version
        shell: pwsh

      - name: Build Sphinx
        run: |
          .\build-sphinx.ps1
        shell: pwsh
        
      - name: QuickFix Temporarily add ROOT_URL to documentation_options.js to fix broken search in sphinx wagtail theme
        run: |
          $file = './build/html/_static/documentation_options.js'
          $content = Get-Content $file -Raw
          $modifiedContent = $content -replace '\};', "`n    URL_ROOT: 'https://hms-is.github.io/mannvirkjaskra-domain-model/',`n};"
          Set-Content -Path $file -Value $modifiedContent
        shell: pwsh

      - name: Upload Artifacts for Deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
